### ISSUE TITLE
Find the Celebrity - Microsoft

### ISSUE THREAD

**Issue by shelcia** [shelcia/noobcodes-docs#105]
https://leetcode.com/problems/find-the-celebrity

**Comment by Kumar-Ankit56** [comment]
@shelcia please assign me.

**Comment by ankushj0801** [comment]
I want to  work on this please assign it to me if it is open. @shelcia

**Comment by ankushj0801** [comment]
Please assign me this if it is open @shelcia

**Comment by Dibyendu303** [comment]
@ankushj0801 close this issue as it is completed
