### ISSUE TITLE
Design Tic-Tac-Toe - Microsoft

### ISSUE THREAD

**Issue by shelcia** [shelcia/noobcodes-docs#106]
https://leetcode.com/problems/design-tic-tac-toe

**Comment by itz-deepak** [comment]
assign this to me

**Comment by ankushj0801** [comment]
I want to  work on this please assign it to me if it is open. @shelcia

**Comment by itz-deepak** [comment]
Not able to access the problem, it is showing subscription required

**Comment by shelcia** [comment]
https://www.lintcode.com/problem/design-tic-tac-toe/note
