### ISSUE TITLE
Delete Node in a BST - Microsoft

### ISSUE THREAD

**Issue by shelcia** [shelcia/noobcodes-docs#127]
https://leetcode.com/problems/populating-next-right-pointers-in-each-node-ii

**Comment by DarK-VEnOM-16** [comment]
I want to work on this

**Comment by ankushj0801** [comment]
I want to  work on this please assign it to me. @shelcia

**Comment by Sparsh752** [comment]
@shelcia Can you assign me this

**Comment by shelcia** [comment]
https://leetcode.com/problems/delete-node-in-a-bst/ Hi my bad !! delete node in bst problem statement is different @DarK-VEnOM-16

**Comment by ankushj0801** [comment]
Can I work on this if it is open? @shelcia
