### ISSUE TITLE
Implement Queue using Stacks - Microsoft

### ISSUE THREAD

**Issue by shelcia** [shelcia/noobcodes-docs#132]
https://leetcode.com/problems/implement-queue-using-stacks

**Comment by sankooru14** [comment]
@shelcia Can you assign it to me?

**Comment by Sparsh752** [comment]
@shelcia Can you assign me this

**Comment by sankooru14** [comment]
@shelcia I would Like to work on this issue
 Can you assign it to me?

**Comment by shelcia** [comment]
anyone working on this ?

**Comment by ankushj0801** [comment]
Please assign me if it is open @shelcia
