### ISSUE TITLE
Sudoku Solver - Microsoft

### ISSUE THREAD

**Issue by shelcia** [shelcia/noobcodes-docs#133]
https://leetcode.com/problems/sudoku-solver

**Comment by sankooru14** [comment]
@shelcia  Can you assign it to me?

**Comment by Sparsh752** [comment]
@shelcia Can you assign me this

**Comment by sankooru14** [comment]
@shelcia I would Like to work on this issue
 Can you assign it to me?

**Comment by ankushj0801** [comment]
Please assign me if it is still open @shelcia
