### ISSUE TITLE
Intersection of Two Linked Lists - Microsoft

### ISSUE THREAD

**Issue by shelcia** [shelcia/noobcodes-docs#134]
https://leetcode.com/problems/intersection-of-two-linked-lists

**Comment by sankooru14** [comment]
@shelcia  Can you assign it to me?

**Comment by Sparsh752** [comment]
@shelcia Can you assign me this

**Comment by sankooru14** [comment]
@shelcia I would Like to work on this issue
 Can you assign it to me?

**Comment by ankushj0801** [comment]
Please assign me if it is open @shelcia
