### ISSUE TITLE
Binary Tree Maximum Path Sum - Microsoft

### ISSUE THREAD

**Issue by shelcia** [shelcia/noobcodes-docs#140]
https://leetcode.com/problems/binary-tree-maximum-path-sum

**Comment by sankooru14** [comment]
@shelcia Can you assign me from #130 to #140 issue?

**Comment by Sparsh752** [comment]
@shelcia Can you assign me this

**Comment by SattyamSamania** [comment]
Hey @shelcia Can I work on this issue?
