### ISSUE TITLE
LFU Cache - Microsoft

### ISSUE THREAD

**Issue by shelcia** [shelcia/noobcodes-docs#145]
https://leetcode.com/problems/lfu-cache

**Comment by nik132-eng** [comment]
Please assign me this issue.

**Comment by Sparsh752** [comment]
@shelcia Can you assign me this

**Comment by ankushj0801** [comment]
Can I work on this if it is open? @shelcia

**Comment by ankushj0801** [comment]
Please assign me if it is open @shelcia
