### ISSUE TITLE
Game of Life - Microsoft

### ISSUE THREAD

**Issue by shelcia** [shelcia/noobcodes-docs#146]
https://leetcode.com/problems/game-of-life

**Comment by nik132-eng** [comment]
Please assign me this issue.

**Comment by sankooru14** [comment]
@shelcia Can you assign it to me?

**Comment by Sparsh752** [comment]
@shelcia Can you assign me this

**Comment by ankushj0801** [comment]
Please assign it to me. @shelcia

**Comment by ankushj0801** [comment]
Please assign this it to me if it is open, I don't think anyone is working on it. @shelcia
