### ISSUE TITLE
Minesweeper - Microsoft

### ISSUE THREAD

**Issue by shelcia** [shelcia/noobcodes-docs#147]
https://leetcode.com/problems/minesweeper

**Comment by nik132-eng** [comment]
Please assign me this issue.

**Comment by sankooru14** [comment]
@shelcia Can you assign this to me?

**Comment by Sparsh752** [comment]
@shelcia Can you assign me this?

**Comment by nik132-eng** [comment]
It needs premium account.
![image](https://user-images.githubusercontent.com/77881638/206368369-28ecc4a6-1169-4e40-84ec-b7fa14c70749.png)

**Comment by ankushj0801** [comment]
Please assign it to me.

**Comment by shelcia** [comment]
https://www.lintcode.com/problem/1189/

**Comment by ankushj0801** [comment]
Can I work on this if it is open? @shelcia
