### ISSUE TITLE
Duplicate Sidebar element

### ISSUE THREAD

**Issue by shelcia** [shelcia/noobcodes-docs#163]
![Screenshot 2022-12-10 at 12 26 03 AM](https://user-images.githubusercontent.com/31156685/206775315-f21189d7-cc3c-4282-a923-981ffa206bfe.png)

**Comment by RavindraP04** [comment]
So, we just have to merge the files of microsoft in one and delete the duplicate ?

**Comment by shivamgupta2020** [comment]
I will work on this.
