### ISSUE TITLE
Strong Password Checker - Adobe

### ISSUE THREAD

**Issue by kshitij01042002** [shelcia/noobcodes-docs#180]
https://leetcode.com/problems/strong-password-checker

**Comment by sankooru14** [comment]
@kshitij01042002 Can you assign this to me?

**Comment by shelcia** [comment]
@kshitij01042002 Please have conversation with @iamatifmoin, he raised PR for the issue you were assigned to. Should I merge or not

**Comment by kshitij01042002** [comment]
@shelcia I have done the changes too.
@iamatifmoin you should have got it addigned before raising the PR
