### ISSUE TITLE
Valid sudoku - uber

### ISSUE THREAD

**Issue by shelcia** [shelcia/noobcodes-docs#37]

**Comment by shivamgupta2020** [comment]
I am interested. Please assign this to me.

**Comment by shivamgupta2020** [comment]
The solution will only be in Python or can also be in any language?

**Comment by shivamgupta2020** [comment]
Also since uber tab isn't present yet so do I have to add new Uber tab or add this page under any different category?

**Comment by shelcia** [comment]
create new tab and add the solution in python or any other major language

**Comment by shivamgupta2020** [comment]
@shelcia I am confused with the code stucture.
Can u please help me with which file I have to edit to create new uber tab?

**Comment by shivamgupta2020** [comment]
ok I added folder named **Uber**.
Then I added code for that.
is that all I have to do?

**Comment by shelcia** [comment]
add config file in uber

**Comment by shivamgupta2020** [comment]
config file == "_category_.json"?

**Comment by shelcia** [comment]
yes like this https://github.com/shelcia/noobcodes-docs/blob/master/docs/adobe/_category_.json

**Comment by shelcia** [comment]
Make sure the numbering is coherent

**Comment by shivamgupta2020** [comment]
but it didnt show the uber tab

**Comment by shelcia** [comment]
npm start running ? try reloading. Also make sure the numbers are right. Atlassian is newly created as well reF: https://github.com/shelcia/noobcodes-docs/pull/61

**Comment by shivamgupta2020** [comment]
ok i will try again

**Comment by shivamgupta2020** [comment]
it worked

**Comment by shivamgupta2020** [comment]
made a PR, please go thorough it and tell me if there is any thing to change.
