### ISSUE TITLE
Three equal parts - Hotstar

### ISSUE THREAD

**Issue by shelcia** [shelcia/noobcodes-docs#38]

**Comment by pranavajith** [comment]
@shelcia 
Could you please explain the issue.

**Comment by shelcia** [comment]
@pranavajith  problem statement: https://leetcode.com/problems/three-equal-parts/

**Comment by pranavajith** [comment]
Can I take this up, @shelcia ?
Also all I have to do is to update the docs folder with another folder called hotstar and create a solution for this problem with proper documentation?

**Comment by shelcia** [comment]
yes

**Comment by ankushj0801** [comment]
Can I work on this if it is open? @shelcia

**Comment by itz-deepak** [comment]
assign this to me
