### ISSUE TITLE
Shortest Word Distance - paypal

### ISSUE THREAD

**Issue by shelcia** [shelcia/noobcodes-docs#73]
https://leetcode.com/problems/shortest-word-distance

**Comment by shivamgupta2020** [comment]
Can't access this page.
Subscription needed.

**Comment by shivamgupta2020** [comment]
this isn't completed yet

**Comment by shelcia** [comment]
https://www.lintcode.com/problem/924/ @shivamgupta2020

**Comment by ankushj0801** [comment]
can I work on this issue if it is open? @shelcia
