### ISSUE TITLE
Jump Game - Blind 75

### ISSUE THREAD

**Issue by shelcia** [shelcia/noobcodes-docs#88]
[Jump Game](https://leetcode.com/problems/jump-game/)

**Comment by shivamgupta2020** [comment]
@shelcia I had made a PR covering all issues from (78-88).
Please merge them.

**Comment by itz-deepak** [comment]
@shivamgupta2020  issue 78 was assigned to me and I have also complted it
Atleast leave a comment before start workin on an issue

**Comment by shivamgupta2020** [comment]
Sorry Biro , my internet was down.
So i was working offline and can't comment.
No problem I will remove that code.

**Comment by shelcia** [comment]
@itz-deepak @shivamgupta2020  do close the issues you have fixed

**Comment by itz-deepak** [comment]
@shelcia close issue option is not visible to me

**Comment by sankooru14** [comment]
@shelcia Can you assign this issue to me?

**Comment by shivamgupta2020** [comment]
@shelcia these issues can only be closed by maintainers. or the one who open issue.
Please close them.
